- name: Update packages
  apt:
    update_cache: yes

- name: Installeren van apache
  apt:
    name: apache2
    state: present

- name: Installeren van PHP
  apt:
    name: php
    state: present

- name: Installeren van php-mysql
  apt:
    name: php-mysql
    state: present

- name: Start en enablen van apache service
  service:
    name: apache2
    state: started
    enabled: yes